### ISSUE TITLE
npm run scss 太慢

### ISSUE THREAD

**Issue by tang-yue** [youknowznm/react-material-blog#1]
cd react-material-blog
npm run scss
运行了很久都没有终止。
运行没有完成。
用cnpm run scss 也是一样的。

**Comment by youknowznm** [comment]
@tang-yue 请看 `package.json` 里 `scss` 命令的内容 `npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive`。这里的 `--watch` 标识使得 `npm run scss` 进程在完成转译 scss 文件后，监听（即 watch）`src` 目录中的文件。因此这个任务是不会自动终止的。
